---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-jwt-secret
  namespace: default
spec:
  encryptedData:
    JWT_SECRET: AgBUNiq6oICY8wIzTovuowfQFBp4X1Klh57Wr6CBrv4UyFJMk0ngW/YPsEv5g1t67QRxDrTN6KX1f13GcT3kGLk/nE5NxKpfxWqs5LB7SBkLBIbMBrO7KA0lpLEUCj4482GtYHCEz9OWH6UH28GxhDtrXK0n0A1ybxtqFE5kJK354UOYLaaQGH9IFknugpe+vFSEK5J+4qD0NcfsuxoGlQTjHKSB9kLHQVDe+PB6xqycXbfC5hpxAy/FCnBJQiSZ/0cwNvNn2Kcwpg9cP983NmjU+g7FEeEFuWBBYFTogrzb7kME1PviWJ4cZRrC3L5a0+Z2AEbaVcIBrWCvdRikybxEumQar7g8Czgd/0bHcBRhBnTBYQEo5TDUOWBouN/ZS6AWftnLX0ZAWfRV6hVZzrMWduVf3Fw/MQTYYaAT/fIvZultcSKAB6OJ+mpF8JRnWw2VtftKQunjgswhcit7JqZ84XKuRQASCjGTS4eynKKzT8H86FMGscAzeTKUo3zgiBHiXeiUTa9gd6Er2J8e5dM7ivnrdFIT0ZI5j8JBLebpYtlVSSKb4UZcTAFYerW/9NHV0h9W4kWHOaefmvwLVeMKIKOViA8k+6DEQvLxChezVd/sfgr/jrtvCOwgvpd1+YAZ9jINveP+YshfjVvHByFPbdGPkm+/q+7sIpWm+3l4kfA9fTKvBS4Uy3gvlflixyNdvt4fFjOV1pr6wcSLMTkkbktR/uLOSC2fuQ81XtCf0IWXCh4aDRawzVHCmA==
  template:
    metadata:
      creationTimestamp: null
      name: backend-jwt-secret
      namespace: default
