apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_NAME: CHANGE_ME_BEFORE_APPLYING
  DB_USER: CHANGE_ME_BEFORE_APPLYING
  DB_PASSWORD: CHANGE_ME_BEFORE_APPLYING
