apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cluster-wellness-local

servers: 1
agents: 0

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer

options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*

kubeAPI:
  host: "0.0.0.0"
